-----------------------------------
-- LANGUAGES
-----------------------------------
INSERT INTO KF2DATABASE.LANGUAGES VALUES(NEXT VALUE FOR KF2DATABASE.LANGUAGES_SEQUENCE, 'en', 'English');
INSERT INTO KF2DATABASE.LANGUAGES VALUES(NEXT VALUE FOR KF2DATABASE.LANGUAGES_SEQUENCE, 'es', 'Español');
INSERT INTO KF2DATABASE.LANGUAGES VALUES(NEXT VALUE FOR KF2DATABASE.LANGUAGES_SEQUENCE, 'fr', 'Français');

-----------------------------------
-- DIFFICULTIES
-----------------------------------
INSERT INTO KF2DATABASE.DIFFICULTIES VALUES (NEXT VALUE FOR KF2DATABASE.DIFFICULTIES_SEQUENCE, '0');
INSERT INTO KF2DATABASE.DIFFICULTIES VALUES (NEXT VALUE FOR KF2DATABASE.DIFFICULTIES_SEQUENCE, '1');
INSERT INTO KF2DATABASE.DIFFICULTIES VALUES (NEXT VALUE FOR KF2DATABASE.DIFFICULTIES_SEQUENCE, '2');
INSERT INTO KF2DATABASE.DIFFICULTIES VALUES (NEXT VALUE FOR KF2DATABASE.DIFFICULTIES_SEQUENCE, '3');

-----------------------------------
-- GAME TYPES
-----------------------------------
INSERT INTO KF2DATABASE.GAME_TYPES(ID, CODE, DIFFICULTY_ENABLED, LENGTH_ENABLED) VALUES (NEXT VALUE FOR KF2DATABASE.GAME_TYPES_SEQUENCE, 'KFGameContent.KFGameInfo_Survival', true, true);
INSERT INTO KF2DATABASE.GAME_TYPES(ID, CODE, DIFFICULTY_ENABLED, LENGTH_ENABLED) VALUES (NEXT VALUE FOR KF2DATABASE.GAME_TYPES_SEQUENCE, 'KFGameContent.KFGameInfo_VersusSurvival', false, false);
INSERT INTO KF2DATABASE.GAME_TYPES(ID, CODE, DIFFICULTY_ENABLED, LENGTH_ENABLED) VALUES (NEXT VALUE FOR KF2DATABASE.GAME_TYPES_SEQUENCE, 'KFGameContent.KFGameInfo_WeeklySurvival', false, false);
INSERT INTO KF2DATABASE.GAME_TYPES(ID, CODE, DIFFICULTY_ENABLED, LENGTH_ENABLED) VALUES (NEXT VALUE FOR KF2DATABASE.GAME_TYPES_SEQUENCE, 'KFGameContent.KFGameInfo_Endless', true, false);
INSERT INTO KF2DATABASE.GAME_TYPES(ID, CODE, DIFFICULTY_ENABLED, LENGTH_ENABLED) VALUES (NEXT VALUE FOR KF2DATABASE.GAME_TYPES_SEQUENCE, 'KFGameContent.KFGameInfo_Objective', true, false);

-----------------------------------
-- LENGTH
-----------------------------------
INSERT INTO KF2DATABASE.LENGTHS VALUES (NEXT VALUE FOR KF2DATABASE.LENGTH_SEQUENCE, '0');
INSERT INTO KF2DATABASE.LENGTHS VALUES (NEXT VALUE FOR KF2DATABASE.LENGTH_SEQUENCE, '1');
INSERT INTO KF2DATABASE.LENGTHS VALUES (NEXT VALUE FOR KF2DATABASE.LENGTH_SEQUENCE, '2');

-----------------------------------
-- MAX PLAYERS
-----------------------------------
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '12');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '11');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '10');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '9');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '8');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '7');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '6');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '5');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '4');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '3');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '2');
INSERT INTO KF2DATABASE.MAX_PLAYERS VALUES (NEXT VALUE FOR KF2DATABASE.MAX_PLAYERS_SEQUENCE, '1');

-----------------------------------
-- OFFICIAL MAPS
-----------------------------------
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-BurningParis', 'KF-BurningParis', 'https://wiki.killingfloor2.com/index.php?title=Burning_Paris','/KFGame/Web/images/maps/KF-BurningParis.jpg', TIMESTAMP('2015-04-21 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-BioticsLab', 'KF-BioticsLab', 'https://wiki.killingfloor2.com/index.php?title=Biotics_Lab_(Killing_Floor_2)','/KFGame/Web/images/maps/KF-BioticsLab.jpg', TIMESTAMP('2015-04-21 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Outpost', 'KF-Outpost', 'https://wiki.killingfloor2.com/index.php?title=Outpost','/KFGame/Web/images/maps/KF-Outpost.jpg', TIMESTAMP('2015-04-21 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-VolterManor', 'KF-VolterManor', 'https://wiki.killingfloor2.com/index.php?title=Volter_Manor','/KFGame/Web/images/maps/KF-VolterManor.jpg', TIMESTAMP('2015-05-26 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Catacombs', 'KF-Catacombs', 'https://wiki.killingfloor2.com/index.php?title=Catacombs','/KFGame/Web/images/maps/KF-Catacombs.jpg', TIMESTAMP('2015-09-01 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-EvacuationPoint', 'KF-EvacuationPoint', 'https://wiki.killingfloor2.com/index.php?title=Evacuation_Point','/KFGame/Web/images/maps/KF-EvacuationPoint.jpg', TIMESTAMP('2015-09-01 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Farmhouse', 'KF-Farmhouse', 'https://wiki.killingfloor2.com/index.php?title=Farmhouse','/KFGame/Web/images/maps/KF-Farmhouse.jpg', TIMESTAMP('2015-12-03 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-BlackForest', 'KF-BlackForest', 'https://wiki.killingfloor2.com/index.php?title=Black_Forest','/KFGame/Web/images/maps/KF-BlackForest.jpg', TIMESTAMP('2015-12-03 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Prison', 'KF-Prison', 'https://wiki.killingfloor2.com/index.php?title=Prison','/KFGame/Web/images/maps/KF-Prison.jpg', TIMESTAMP('2016-04-07 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-ContainmentStation', 'KF-ContainmentStation', 'https://wiki.killingfloor2.com/index.php?title=Containment_Station','/KFGame/Web/images/maps/KF-ContainmentStation.jpg', TIMESTAMP('2016-06-13 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-HostileGrounds', 'KF-HostileGrounds', 'https://wiki.killingfloor2.com/index.php?title=Hostile_Grounds','/KFGame/Web/images/maps/KF-HostileGrounds.jpg', TIMESTAMP('2016-06-13 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-InfernalRealm', 'KF-InfernalRealm', 'https://wiki.killingfloor2.com/index.php?title=Infernal_Realm','/KFGame/Web/images/maps/KF-InfernalRealm.jpg', TIMESTAMP('2016-08-25 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-ZedLanding', 'KF-ZedLanding', 'https://wiki.killingfloor2.com/index.php?title=ZED_Landing','/KFGame/Web/images/maps/KF-ZedLanding.jpg', TIMESTAMP('2017-01-19 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Nuked', 'KF-Nuked', 'https://wiki.killingfloor2.com/index.php?title=Nuked','/KFGame/Web/images/maps/KF-Nuked.jpg', TIMESTAMP('2017-03-21 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-TheDescent', 'KF-TheDescent', 'https://wiki.killingfloor2.com/index.php?title=The_Descent','/KFGame/Web/images/maps/KF-TheDescent.jpg', TIMESTAMP('2017-03-21 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-TragicKingdom', 'KF-TragicKingdom', 'https://wiki.killingfloor2.com/index.php?title=The_Tragic_Kingdom','/KFGame/Web/images/maps/KF-TragicKingdom.jpg', TIMESTAMP('2017-06-13 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Nightmare', 'KF-Nightmare', 'https://wiki.killingfloor2.com/index.php?title=Nightmare','/KFGame/Web/images/maps/KF-Nightmare.jpg', TIMESTAMP('2017-10-17 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-KrampusLair', 'KF-KrampusLair', 'https://wiki.killingfloor2.com/index.php?title=Krampus_Lair','/KFGame/Web/images/maps/KF-KrampusLair.jpg', TIMESTAMP('2017-12-12 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-DieSector', 'KF-DieSector', 'https://wiki.killingfloor2.com/index.php?title=DieSector','/KFGame/Web/images/maps/KF-DieSector.jpg', TIMESTAMP('2017-12-12 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-PowerCore_Holdout', 'KF-PowerCore_Holdout', 'https://wiki.killingfloor2.com/index.php?title=Powercore','/KFGame/Web/images/maps/KF-PowerCore_Holdout.jpg', TIMESTAMP('2017-12-12 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Airship', 'KF-Airship', 'https://wiki.killingfloor2.com/index.php?title=Airship','/KFGame/Web/images/maps/KF-Airship.jpg', TIMESTAMP('2018-06-12 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Lockdown', 'KF-Lockdown', 'https://wiki.killingfloor2.com/index.php?title=Lockdown','/KFGame/Web/images/maps/KF-Lockdown.jpg', TIMESTAMP('2018-06-12 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-MonsterBall', 'KF-MonsterBall', 'https://wiki.killingfloor2.com/index.php?title=Monster_Ball','/KFGame/Web/images/maps/KF-MonsterBall.jpg', TIMESTAMP('2018-10-02 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-SantasWorkshop', 'KF-SantasWorkshop', 'https://wiki.killingfloor2.com/index.php?title=Santa%27s_Workshop','/KFGame/Web/images/maps/KF-SantasWorkshop.jpg', TIMESTAMP('2018-12-04 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-ShoppingSpree', 'KF-ShoppingSpree', 'https://wiki.killingfloor2.com/index.php?title=Shopping_Spree','/KFGame/Web/images/maps/KF-ShoppingSpree.jpg', TIMESTAMP('2018-12-04 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Spillway', 'KF-Spillway', 'https://wiki.killingfloor2.com/index.php?title=Spillway','/KFGame/Web/images/maps/KF-Spillway.jpg', TIMESTAMP('2019-03-26 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-SteamFortress', 'KF-SteamFortress', 'https://wiki.killingfloor2.com/index.php?title=Steam_Fortress','/KFGame/Web/images/maps/KF-SteamFortress.jpg', TIMESTAMP('2019-06-18 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-AshwoodAsylum', 'KF-AshwoodAsylum', 'https://wiki.killingfloor2.com/index.php?title=Ashwood_Asylum','/KFGame/Web/images/maps/KF-AshwoodAsylum.jpg', TIMESTAMP('2019-10-01 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Sanitarium', 'KF-Sanitarium', 'https://wiki.killingfloor2.com/index.php?title=Sanitarium','/KFGame/Web/images/maps/KF-Sanitarium.jpg', TIMESTAMP('2019-12-10 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Biolapse', 'KF-Biolapse', 'https://wiki.killingfloor2.com/index.php?title=Biolapse','/KFGame/Web/images/maps/KF-Biolapse.jpg', TIMESTAMP('2020-03-24 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Desolation', 'KF-Desolation', 'https://wiki.killingfloor2.com/index.php?title=Desolation','/KFGame/Web/images/maps/KF-Desolation.jpg', TIMESTAMP('2020-06-08 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-HellmarkStation', 'KF-HellmarkStation', 'https://wiki.killingfloor2.com/index.php?title=Hellmark_Station','/KFGame/Web/images/maps/KF-HellmarkStation.jpg', TIMESTAMP('2020-09-29 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Elysium', 'KF-Elysium', 'https://wiki.killingfloor2.com/index.php?title=Elysium','/KFGame/Web/images/maps/KF-Elysium.jpg', TIMESTAMP('2020-12-08 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Dystopia2029', 'KF-Dystopia2029', 'https://wiki.killingfloor2.com/index.php?title=Dystopia_2029','/KFGame/Web/images/maps/KF-Dystopia2029.jpg', TIMESTAMP('2021-03-23 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Moonbase', 'KF-Moonbase', 'https://wiki.killingfloor2.com/index.php?title=Moonbase','/KFGame/Web/images/maps/KF-Moonbase.jpg', TIMESTAMP('2021-06-22 00:00:00'));
INSERT INTO KF2DATABASE.MAPS(ID, CODE, ALIAS, URL_INFO, URL_PHOTO, RELEASE_DATE) VALUES (NEXT VALUE FOR KF2DATABASE.MAPS_SEQUENCE, 'KF-Netherhold', 'KF-Netherhold', 'https://wiki.killingfloor2.com/index.php?title=Netherhold','/KFGame/Web/images/maps/KF-Netherhold.jpg', TIMESTAMP('2021-10-05 00:00:00'));

INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BurningParis');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BioticsLab');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Outpost');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-VolterManor');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Catacombs');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-EvacuationPoint');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Farmhouse');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BlackForest');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Prison');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ContainmentStation');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-HostileGrounds');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-InfernalRealm');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ZedLanding');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Nuked');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-TheDescent');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-TragicKingdom');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Nightmare');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-KrampusLair');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-DieSector');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-PowerCore_Holdout');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Airship');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Lockdown');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-MonsterBall');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-SantasWorkshop');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ShoppingSpree');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Spillway');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-SteamFortress');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-AshwoodAsylum');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Sanitarium');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Biolapse');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Desolation');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-HellmarkStation');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Elysium');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Dystopia2029');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Moonbase');
INSERT INTO KF2DATABASE.OFFICIAL_MAPS(ID) VALUES (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Netherhold');

-----------------------------------
-- PROFILES
-----------------------------------
INSERT INTO KF2DATABASE.PROFILES(ID, NAME, ID_LANGUAGE, ID_GAMETYPE, ID_MAP, ID_DIFFICULTY, ID_LENGTH, ID_MAXPLAYERS, SERVER_NAME, WEB_PORT, GAME_PORT, QUERY_PORT, WEB_PAGE, TAKEOVER, TEAM_COLLISION, ADMIN_CAN_PAUSE, ANNOUNCE_ADMIN_LOGIN, MAP_VOTING, KICK_VOTING, PUBLIC_CHAT, SPECTATORS_ONLY_CHAT_OTHER_SPECTATORS, VOIP, CHAT_LOGGING, MAP_VOTING_TIME, KICK_PERCENTAGE, CHAT_LOGGING_FILE_TIMESTAMP, TIME_BETWEEN_KICK_VOTES, MAX_IDLE_TIME, DEAD_PLAYERS_CAN_TALK, MAX_SPECTATORS, MAP_OBJETIVES, PICK_UP_ITEMS, FRIENDLY_FIRE_PERCENTAGE, READY_UP_DELAY, GAME_START_DELAY)
VALUES (
	NEXT VALUE FOR KF2DATABASE.PROFILES_SEQUENCE,
	'Default',
	(SELECT ID FROM KF2DATABASE.LANGUAGES WHERE CODE='en'),
	(SELECT ID FROM KF2DATABASE.GAME_TYPES WHERE CODE='KFGameContent.KFGameInfo_Survival'),
	(SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BurningParis'),
	(SELECT ID FROM KF2DATABASE.DIFFICULTIES WHERE CODE='0'),
	(SELECT ID FROM KF2DATABASE.LENGTHS WHERE CODE='0'),
	(SELECT ID FROM KF2DATABASE.MAX_PLAYERS WHERE CODE='6'),
	'Killing Floor 2 Server', 8080, 7777, 27015, true, false, true, false, true, true, true, true, false, true, false, 60, 0.66, true, 10, 0, true, 2, true, true, 0, 90, 4
);


-----------------------------------
-- PROFILES_MAPS
-----------------------------------

INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BurningParis'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BioticsLab'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Outpost'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-VolterManor'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Catacombs'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-EvacuationPoint'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Farmhouse'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-BlackForest'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Prison'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ContainmentStation'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-HostileGrounds'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-InfernalRealm'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ZedLanding'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Nuked'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-TheDescent'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-TragicKingdom'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Nightmare'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-KrampusLair'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-DieSector'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-PowerCore_Holdout'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Airship'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Lockdown'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-MonsterBall'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-SantasWorkshop'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-ShoppingSpree'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Spillway'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-SteamFortress'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-AshwoodAsylum'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Sanitarium'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Biolapse'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Desolation'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-HellmarkStation'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Elysium'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Dystopia2029'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Moonbase'), CURRENT TIMESTAMP);
INSERT INTO KF2DATABASE.PROFILES_MAPS (ID_PROFILE, ID_MAP, IMPORTED_DATE) VALUES ((SELECT ID FROM KF2DATABASE.PROFILES WHERE NAME='Default'), (SELECT ID FROM KF2DATABASE.MAPS WHERE CODE='KF-Netherhold'), CURRENT TIMESTAMP);
